#!/usr/bin/env python

from terminal.builtin import Command
import init

program = Command(
    'init',
    description='init a project',
    version=init.__version__
)


@program.action
def license(name=None):
    """
    Show available licenses.

    :param name: the name of the license
    """
    pass


program.parse()
