#!/usr/bin/env python

import sys
import datetime
from terminal.builtin import Command
import init

program = Command(
    'init',
    description='init a project',
    version=init.__version__
)


@program.action
def license(year=None, organization=None):
    """
    Show available licenses.

    :param year: the copyright year
    :param organization: the organization name of the project

    :option organization: --organization [name]
    """

    from init import license

    args = filter(lambda o: not o.startswith('-'), program.args)

    if not year:
        year = datetime.datetime.utcnow().year

    if year:
        year = int(year)

    if args:
        name = args[0]
        data = license.parse(
            name,
            year=year,
            organization=organization,
        )
        if not data:
            print('Not Found')
            return
        sys.stdout.write(data)
    else:
        print('\t'.join(license.licenses()))
    return sys.exit()


@program.action
def update(name=None):
    """
    Update templates in ~/.init-template/
    """
    pass


@program.action
def install(name):
    """
    Install a template to ~/.init-template/

    :param name: name of the template scaffold
    """
    if '/' in name:
        url = 'git://github.com/%s' % name
    else:
        url = 'git://github.com/init-template/%s' % name
    pass


program.parse()
